version: "3.7"
services:
  app:
      build:
          context: .
          dockerfile: docker/php/Dockerfile
          args:
              TZ: Europe/Moscow
              USER_GROUP_ID: 1000
              USER_ID: 1000
      image: digitalocean.com/php
      restart: unless-stopped
      tty: true
      environment:
          - SERVICE_TAGS=dev
      working_dir: /var/www
      volumes:
          - ./:/var/www
          - ./../../.ssh:/home/www/.ssh
          - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      networks:
          - internal
      depends_on:
          - db
          - redis
          - rabbitmq

  db:
    image: mariadb:10.5
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: laravelpassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - internal

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - internal

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - internal

  nginx:
      image: nginx:alpine
      restart: unless-stopped
      tty: true
      environment:
          NGINX_ENVSUBST_TEMPLATE_SUFFIX: ".conf"
          FASTCGI_PASS: "volog-app-1:9000"
      ports:
        - "8083:80"
      volumes:
          - ./:/var/www
          - ./docker/nginx/templates:/etc/nginx/templates
          - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      networks:
          - internal
          - web
      depends_on:
          - app

networks:
    web:
        external: true
    internal:
        external: false

volumes:
  db_data:
